### ISSUE TITLE
bug with ubuntu server 16.04 might be only with app-names that have numbers or has a hyphens [-] in the app name

### ISSUE THREAD

**Issue by raykai** [dfinnema/le-serverpilot#30] opened 2016-04-25 23:50 UTC
seems that with ubuntu server 16.04 and serverpilot when using the ssl config as test dummy 

when we activate SSL option 8  and then get to the end where it ask to reboot :
`Do you want to RESTART Nginx & Apache service (y/n)?`
` - needed to reflect changes`

and say Y  it says  `+ Done` but ether Apache or Nginx did not reboot well as all website dont respond i tested them both with http and https. 

to get them working i had to reboot the server . i tested this with 2 servers both do the same i didint test using out of dummy SSL config tho

**Comment by dfinnema** [comment] 2016-04-25 23:58
At this time 16.04 is not Supported yet. As per requirements 14.04 is currently supported.

**Comment by raykai** [comment] 2016-04-26 00:30
my Apache log is giving a error : `server certificate does NOT include an ID which matches the server name`

no error in the nginx logs so thats good 

il do more testing

**Comment by raykai** [comment] 2016-04-26 01:15
it seams like apache dose reboot but not nginx when using the option 8  if i manually send a commend sudo service nginx-sp restart websites start working in http but not in https.

**Comment by alaric1** [comment] 2016-05-08 20:52
i can confirm that its not working on Ubuntu 16.04

**Comment by dfinnema** [comment] 2016-05-10 23:35
Just having a look at this now. I am having trouble reproducing your errors.

**My Steps**
1. Created a new droplet on Digital Ocean (Ubuntu 16.04 x64)
2. Added Serverpilot to the Server
3. Loaded le-serverpilot from github as per README (I tried the development version)
4. Created a dummy certificate and applied it
5. Revoked dummy cert and created a real one.

I had no errors can you please let me know your steps so I can fix this issue?

<img width="490" alt="screen shot 2016-05-11 at 11 35 04" src="https://cloud.githubusercontent.com/assets/5592013/15165755/721a45c2-176c-11e6-9baa-e9a786f0015b.png">

**Comment by raykai** [comment] 2016-05-12 02:23
are the website working on https after that ?

**Comment by dfinnema** [comment] 2016-05-12 02:24
I have setup a test server here 
https://u16.venire.xyz/

**Comment by raykai** [comment] 2016-05-12 02:26
that's wired i tested it 4 times ... il start a new server and test it ones more.

**Comment by raykai** [comment] 2016-05-12 04:25
i cant seam to get it working i get the same log:

![3](https://cloud.githubusercontent.com/assets/8138894/15204030/4243ef0e-17d7-11e6-8237-cafd50e66dfe.JPG)

but then the website crashes:

http:
![4](https://cloud.githubusercontent.com/assets/8138894/15204062/8692c34c-17d7-11e6-9aec-0e49de02ba6a.JPG)
 
apache error log : 
`[Thu May 12 00:18:05.910450 2016] [ssl:warn] [pid 2519:tid 139882741335936] AH01909: server-aquaexotik0cms:443:0 server certificate does NOT include an ID which matches the server name
`

**Comment by raykai** [comment] 2016-05-12 04:36
my apache-sp error log:
[Thu May 12 00:18:03.814313 2016] [mpm_event:notice] [pid 1515:tid 140663426410368] AH00491: caught SIGTERM, shutting down

[Thu May 12 00:18:05.690609 2016] [suexec:notice] [pid 2518:tid 139882741335936] AH01232: suEXEC mechanism enabled (wrapper: /opt/sp/apache/bin/suexec)

[Thu May 12 00:18:05.904528 2016] [auth_digest:notice] [pid 2519:tid 139882741335936] AH01757: generating secret for digest authentication ...

[Thu May 12 00:18:05.924604 2016] [mpm_event:notice] [pid 2519:tid 139882741335936] AH00489: Apache/2.4.18 (Unix) OpenSSL/1.0.2g-fips configured -- resuming normal operations

[Thu May 12 00:18:05.924795 2016] [core:notice] [pid 2519:tid 139882741335936] AH00094: Command line: '/opt/sp/apache/bin/httpd'

**Comment by raykai** [comment] 2016-05-12 04:43
if i deactivate SLL then all websites comes back online.

il try with a new server and report back.

**Comment by raykai** [comment] 2016-05-12 04:54
can it be because my app name has a number in it ? aquaexotik0cms there is a zero before the cms can u try with an app name with a zero in it ?

**Comment by raykai** [comment] 2016-05-12 05:34
seams to only work with apps name with out numbers in them on my side.

 there is an other bug if using multiple domains exp: abc.com www.abc.com 

we need to enter some thing on this line:

`If you are using SNI please enter the PRIMARY domain`
`   if using multiple domains please use the first one`   
    `NOT using SNI? You can leave this blank`

if we do enter something on this line it dont show the certs for them all just the 1st domain that we enter on the line just before the other domains will have a error Your connection is not secure.

**Comment by raykai** [comment] 2016-05-14 21:01
does the same if the app name has a dash in it like this:  abc-forum

**Comment by alaric1** [comment] 2016-05-14 21:52
that could make seance as i have hyphens in my apps name ... hope there is a way to get it to work i have many apps with hyphens would be a pain to change the name of them all.

**Comment by alaric1** [comment] 2016-05-14 22:10
i seam to have the same error in my apache error log

`server-the-blue-community:443:0 server certificate does NOT include an ID which matches the server name`

**Comment by raykai** [comment] 2016-05-18 20:07
are we going to need to setup a new server just to get the apps name right or is there a way to fix the code for it to work with numbers and hyphens ?

**Comment by dfinnema** [comment] 2016-05-19 09:50
Just had some time to test this

My test domains working without issue (using the development branch - updated a JSON issue)
https://aquaexotik0cms.venire.xyz/
https://test-123.venire.xyz/

Can you check with the new version to see if this resolved it (use a brand new droplet to ensure no previous configs are conflicting).

**Comment by raykai** [comment] 2016-05-19 10:28
is the app name have numbers  im not talking about the domain name.

**Comment by dfinnema** [comment] 2016-05-19 10:30
I have the app name the same as those domains. Did you have an app name that you are having trouble with?

**Comment by raykai** [comment] 2016-05-19 10:33
yup all the ones that have ether a - or numbers are not working this is wired ... 
![123](https://cloud.githubusercontent.com/assets/8138894/15390755/911f1a36-1d8b-11e6-840d-d0dbed6dce40.JPG)

**Comment by raykai** [comment] 2016-05-19 10:34
let me test it with the new update 
 its ether that or im not setting the ssl the right way  tho ssl is working on my other domains that dont have - in them

**Comment by dfinnema** [comment] 2016-05-19 10:34
Happy to point some test domains at your server if you need some spare ones

**Comment by raykai** [comment] 2016-05-19 10:42
getting errors with new update when creating a cert dummy test 

` ###############################################################
 ##      THIS WILL ISSUE A FREE 90 DAY SSL CERTIFICATE        ##
 ##                     FROM LETS ENCRYPT                     ##
 ###############################################################

Do you want to ISSUE a SSL certificate (y/n)?
 > existing certificates are renewed if older than 14 days
y

Which domain(s) do you wish to issue a certificate for?
 > eg; mydomain.com
 > For more than one SSL cert per IP,
   please use spaces in between for any SNI domains
 > eg; mydomain.com myseconddomain.com someothergreatdomain.com

   NOTE: www.mydomain and mydomain are not the same and need to be
         added seperatly using SNI

aquaexotik.ca

 - global auto challange directory exists
 + No changes needed in Vhosts
 + Using config file /etc/le-serverpilot/tmp.df
 + Challenge directory found
 + Processing aquaexotik.ca
 + Challenge directory found
 ERROR: Cannot reach the Challenge dir using http (ERROR: 521)
`

**Comment by raykai** [comment] 2016-05-19 10:44
nvm server crashed when updating to the new update ...

**Comment by dfinnema** [comment] 2016-05-19 10:44
Can you access the following url in your browser 

http://MYDOMAIN.com/.well-known/acme-challenge/df768768.txt

**Comment by raykai** [comment] 2016-05-19 10:46
that link is giving a 404

**Comment by raykai** [comment] 2016-05-19 10:46
![254](https://cloud.githubusercontent.com/assets/8138894/15391121/73f7b1c8-1d8d-11e6-924e-31a14ec5acae.JPG)

**Comment by dfinnema** [comment] 2016-05-19 10:47
You do have to substitute MYDOMAIN with your actual testing one..

**Comment by raykai** [comment] 2016-05-19 10:47
LOL my bad >_<

**Comment by raykai** [comment] 2016-05-19 10:48
this is my website http://aquaexotik.ca/

**Comment by dfinnema** [comment] 2016-05-19 10:49
So the ACME challange dir is working
http://aquaexotik.ca/.well-known/acme-challenge/df768768.txt

Can you try again?

**Comment by raykai** [comment] 2016-05-19 10:51
should i test it with ssl on ? or off ...

when ssl is off its giving me a its all working!

**Comment by raykai** [comment] 2016-05-19 10:52
creating a new test cert 1 sec

**Comment by raykai** [comment] 2016-05-19 10:55
ok try https://aquaexotik.ca  its not going to work it will send you back to http

**Comment by dfinnema** [comment] 2016-05-19 10:58
Thats because you are using a cloudflare server (when the orange cloud is turned off does it work correctly?)

**Comment by raykai** [comment] 2016-05-19 10:58
if i go say on a app with no - or numbers it works : https://drive.raykai.tk/

**Comment by raykai** [comment] 2016-05-19 10:59
let me tern off cloudflare

**Comment by dfinnema** [comment] 2016-05-19 10:59
with your https://drive.raykai.tk/ does it work when you create a new app with a number or - in it?

**Comment by raykai** [comment] 2016-05-19 11:01
hmmm working now that i have cloudflare off .... why did it work with ubuntu 14.04 with cloudflare on ..

**Comment by dfinnema** [comment] 2016-05-19 11:03
not sure but my test server using the latest development branch is working with a number and / or dash in the app and / or domain name without issue on 14.04 and 16.04.

**Comment by raykai** [comment] 2016-05-19 11:03
i had crypto on cloudflare off so it should still work no ?

**Comment by dfinnema** [comment] 2016-05-19 11:03
Cloudflare does a lot behind the scenes so I am not sure sorry

**Comment by dfinnema** [comment] 2016-05-19 11:05
I am closing this issue as I cannot replicate the bugs. Feel free to open a new issue if there is anything else though

**Comment by raykai** [comment] 2016-05-19 11:06
this is real wired i pout cloudflare back on and its working ...

**Closed by dfinnema** 2016-05-19 11:05 UTC

**Comment by dfinnema** [comment] 2016-05-19 11:07
Might just be that the cache that cloudflare uses creates issues
